### ISSUE TITLE
How about AMQP headers?

### ISSUE THREAD

**Issue by dmaone** [CJWorkbench/carehare#6]
I need AMQP header access for received messages.
Looks like overriding `next_delivery()` (either by subclassing or plain old monkey-patching) should do the trick, but it would be nice to have `next_delivery_with_headers()` available out of the box (with a better name, probably..). Do you accept PRs? What would you suggest for a function name?

Also, ability to set queue arguments would be nice - `x-stream-offset` argument in particular, to use with rabbitmq streams.

PS: That `asyncio.wait()` trick in `_next_delivery()` is really awesome! I was _really_ wary of `asyncio.wait_for()` for as long as I can remember, but couldn't find a decent solution.

**Comment by adamhooper** [comment]
Great requests! Yes, PRs are welcome. These are features that would fit perfectly but haven't been needed until you came along :).

I think `next_delivery_as_pamqp()` sounds nicest to me. It could return the `_Delivery` -- renamed `PamqpDelivery` and without any helper methods.... And then `next_delivery()` could rely on it.

I can't take credit for inventing some new idea with the `.wait()` trick. It's a primitive in every other language I've used. It's also a primitive _internally_ in CPython; but asyncio and the other Python event-loop libraries obfuscate the simple stuff.

**Comment by dmaone** [comment]
the `.wait()` is in every language indeed. But passing the future whose only purpose is to signal it's time to get out of waiting - that's the thing I haven't yet seen.

As for renaming `_Delivery` - this will introduce an extra copy, and I'm not a fan of that.
I'm also not sure what helper methods are doing on the _Delivery, tbh.
I mean, `add_HEADER()` I semi-understand, pylint might be mad about "using protected method" which shouldn't be protected.
But `add_BODY()` is simply an inefficient way to write `self._delivery.body.append(frame)` - lists are mutable, even though NamedTuple itself isn't :)
It looks like you wanted a mutable `NamedTuple`, really. Closest thing in python would be the `dataclass` - can I make it a `dataclass` in PR?

**Comment by adamhooper** [comment]
I prefer NamedTuple over dataclasses because I'm obsessed with
immutability. It's more Erlangish than Pythonic; but then, so is RabbitMQ.
Compelling benchmarks would change my mind.

The `_replace()` being protected is frustrating; I'd probably write the
whole thing out explicitly -- `return PamqpDelivery(..., ...,
...)`. And yeah, copying the BODY is fine -- again, benchmarks would sway
me.

I used four Pythonic RabbitMQ clients in production before I sat down to
write Carehare. This way is better :).

**Comment by dmaone** [comment]
> I used four Pythonic RabbitMQ clients in production before I sat down to write Carehare.

And it shows. (Thanks, btw - it's really nice how it takes away from me all the flexibility nobody _really_ needs while allowing to do what's really needed.)

However, python doesn't have even a slither of parallelism Erlang has, so one is stuck with a single thread (yes, The GIL) and immutability becomes quite expensive all of a sudden. I'll be back with benchmarks.

**Comment by dmaone** [comment]
So, it looks like immutability bears a hefty price tag - and without massive parallelism to hide it, it's quite painful :)

On python 3.10.2, i7-10750H, WSL:
Replacing object every time: 1 append 1015us, 10 appends 7954us -> 771ns.
Wrapped into function call: 363us and 1186us -> 92ns
Direct append: 311us and 708us -> 44ns, 17.5x (yes, "17500%" :) ) faster.
Looks like rest of the test is 267/271/244ns - consistent-ish, so benchmark doesn't seem to be terribly wrong.

Update: and dataclass is 1-2% slower than NamedTuple - although that particular result isn't terribly consistent.

Benchmark itself (cutting out repetitive pieces):
```
from timeit import timeit
from typing import NamedTuple

NUM_TESTS = 1000000

class TestImmutable(NamedTuple):
    body: list[str] = []

    def add(self, body: str):
        return self._replace(body=self.body + [body])

class TestMutable(NamedTuple):
    body: list[str] = []

    def add(self, body: str):
        self.body.append(body)

def print_time(msg, timed, baseline):
    print(f"{msg:<50s}: {timed:.3f}s, speedup: {baseline/timed:.2f}")

def run_immutable(msg, data, baseline):
    def add():
        obj = TestImmutable()
        obj = obj.add(data)

    timed = timeit(add, number=NUM_TESTS)
    print_time(msg, timed, baseline)
    return timed

[skip]

compare_to = run_immutable("100b IMMutable", c100, 0)
run_mutable_function("100b Mutable fun", c100, compare_to)
run_mutable_direct("100b Mutable direct", c100, compare_to)
run_immutable("100b IMMutable", c100, compare_to)
```
"fun" is replacing `_replace()` with `self.body.append(body)`, "direct" is simply doing that without a function. Second "immutable" tests are to check for presence of cache effects

Results:

One append:
```
100b IMMutable                                    : 1.049s, speedup: 0.00
100b Mutable fun                                  : 0.363s, speedup: 2.89
100b Mutable direct                               : 0.311s, speedup: 3.37
100b IMMutable                                    : 1.015s, speedup: 1.03
-----
1k IMMutable                                      : 1.066s, speedup: 0.00
1k Mutable fun                                    : 0.369s, speedup: 2.89
1k Mutable direct                                 : 0.298s, speedup: 3.58
1k IMMutable                                      : 1.039s, speedup: 1.03
-----
10k IMMutable                                     : 1.053s, speedup: 0.00
10k Mutable fun                                   : 0.366s, speedup: 2.88
10k Mutable direct                                : 0.304s, speedup: 3.46
10k IMMutable                                     : 1.064s, speedup: 0.99
-----
100k IMMutable                                    : 1.045s, speedup: 0.00
100k Mutable fun                                  : 0.373s, speedup: 2.80
100k Mutable direct                               : 0.310s, speedup: 3.37
100k IMMutable                                    : 1.063s, speedup: 0.98
```

Two appends:
```
100b IMMutable                                    : 1.811s, speedup: 0.00
100b Mutable fun                                  : 0.459s, speedup: 3.95
100b Mutable direct                               : 0.354s, speedup: 5.12
100b IMMutable                                    : 1.766s, speedup: 1.03
-----
100k IMMutable                                    : 1.829s, speedup: 0.00
100k Mutable fun                                  : 0.456s, speedup: 4.01
100k Mutable direct                               : 0.363s, speedup: 5.04
100k IMMutable                                    : 1.839s, speedup: 0.99
```

Three appends:
```
100b IMMutable                                    : 2.602s, speedup: 0.00
100b Mutable fun                                  : 0.570s, speedup: 4.57
100b Mutable direct                               : 0.395s, speedup: 6.58
100b IMMutable                                    : 2.564s, speedup: 1.01
-----
100k IMMutable                                    : 2.661s, speedup: 0.00
100k Mutable fun                                  : 0.564s, speedup: 4.71
100k Mutable direct                               : 0.397s, speedup: 6.70
100k IMMutable                                    : 2.641s, speedup: 1.01
```

Five appends:
```
100b IMMutable                                    : 4.140s, speedup: 0.00
100b Mutable fun                                  : 0.762s, speedup: 5.43
100b Mutable direct                               : 0.479s, speedup: 8.65
100b IMMutable                                    : 4.000s, speedup: 1.03
-----
100k IMMutable                                    : 4.146s, speedup: 0.00
100k Mutable fun                                  : 0.799s, speedup: 5.19
100k Mutable direct                               : 0.483s, speedup: 8.59
100k IMMutable                                    : 3.974s, speedup: 1.04
```

Ten appends:
```
100b IMMutable                                    : 8.175s, speedup: 0.00
100b Mutable fun                                  : 1.186s, speedup: 6.89
100b Mutable direct                               : 0.708s, speedup: 11.55
100b IMMutable                                    : 7.954s, speedup: 1.03
-----
1k IMMutable                                      : 7.952s, speedup: 0.00
1k Mutable fun                                    : 1.227s, speedup: 6.48
1k Mutable direct                                 : 0.671s, speedup: 11.84
1k IMMutable                                      : 7.874s, speedup: 1.01
-----
10k IMMutable                                     : 7.996s, speedup: 0.00
10k Mutable fun                                   : 1.216s, speedup: 6.57
10k Mutable direct                                : 0.730s, speedup: 10.95
10k IMMutable                                     : 7.855s, speedup: 1.02
-----
100k IMMutable                                    : 8.108s, speedup: 0.00
100k Mutable fun                                  : 1.241s, speedup: 6.53
100k Mutable direct                               : 0.667s, speedup: 12.16
100k IMMutable                                    : 7.976s, speedup: 1.02
```

**Comment by adamhooper** [comment]
Ooh awesome! Thanks for the numbers.

Now the real test: how many more RabbitMQ messages per second can we
process with mutable?

**Comment by dmaone** [comment]
This is a wrong question to ask, really.
Carehare isn't the main application, it's a library - so it's ideal overhead is zero. The less resources it uses, the more is left for actual business logic - and, again, in python environment we're essentially talking a single thread, it's not parallelizable.

**Comment by adamhooper** [comment]
Here's my totally-untested assumption: `async for` costs 10,000x more than
`_replace`.

I could be wrong. But that's where we disagree. I'm thinking: if the change
you propose to this library doesn't make anybody's life better, and it
makes my life worse, then it isn't worth it.

Except for being "Pythonic." But carehare is proudly un-Pythonic :).

**Comment by dmaone** [comment]
..but at 10 frames - which are ~2.5MB message - it's ~8 microseconds to just append them to the Delivery. So, if we're doing nothing but that - ~130k messages per second will be the limit. But for 1000 messages per second it will be - again, approximately - 1% of the total machine processing capacity will be spent on just appending a frame to the message.

`async for` is a dumpster fire, I'm not gonna use it (and, btw, it makes processing sequential - even if your message processing is awaiting on something, `async for` won't start processing another message during that time. This is OK until you suddenly find yourself with a huge backlog while being unable to use even 50% of a single CPU core :) ). But even then - it's definitely faster than creating a new object plus disposal of an old one.

**Comment by adamhooper** [comment]
Your logic is as compelling as pure math can be. But is 1,000 messages per
second a lot? A little? I don't know. Is 2.5MB per message sane? Crazy? I
don't know (but probably crazy).

I haven't benchmarked Carehare. It focuses on correctness first -- hence
its comical adherence to immutability. Speed is certainly important to me;
so is my joyful irreverence for Python ;). It's all a balance.

And it's about people. Who needs this speed? What impact will it have? I
don't know. ... In the meantime, benchmarks (not micro-benchmarks) are a
proxy that can let me imagine the rest.

**Comment by dmaone** [comment]
1kmps is a lot - for python.
2.5MB/message is definitely crazy - but sadly it's the world I'm living in (also 256kB max frame size is what I remember to be a default. It's configurable, but..). I've seen 5MB. I haven't yet seen 10MB, but I'm afraid it's only matter of time.

Correctness is good - but perf is kinda important too (although, this being python, I understand how stupid I sound right now - because if one cares for perf, the only answer is "use a less clowny language").

Anyway. I monkeypatched what I wanted in a way that isn't likely to break, so I'm good :)
