### ISSUE TITLE
persistent message publishing

### ISSUE THREAD

**Issue by dmaone** [CJWorkbench/carehare#7]
Looks like carahare can only publish transient messages - all of which will be gone after rabbitmq cluster restarts (even though with lazy queues they'll be persisted to disk).

Is that an intended way?

**Comment by adamhooper** [comment]
It's just all that's been asked for so far. You're welcome to create a PR to add another message option.

My one proviso is: only add it if you're gonna use it :). We don't want to maintain unused features :).
